// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27mE9mq0oJzWLxg4FH8TQxWMb3yKFQ_g',
    appId: '1:411848934626:android:90a1edc94be5834eff4abb',
    messagingSenderId: '411848934626',
    projectId: 'taskmanager-1dc4d',
    storageBucket: 'taskmanager-1dc4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxUprxbPUJLAP2QFg8O0atoI4asNirfM',
    appId: '1:411848934626:ios:284f497d1e43d3dbff4abb',
    messagingSenderId: '411848934626',
    projectId: 'taskmanager-1dc4d',
    storageBucket: 'taskmanager-1dc4d.firebasestorage.app',
    androidClientId: '411848934626-lim21norlbjlshidh882hnc6rd3ad1ph.apps.googleusercontent.com',
    iosClientId: '411848934626-1vjuc1nmesfcgnbfqgf4pon0prenm5h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjpQuvgkxJTAOIVPfTA1bBNJsDTNtVeQc',
    appId: '1:411848934626:web:565922e72089db6cff4abb',
    messagingSenderId: '411848934626',
    projectId: 'taskmanager-1dc4d',
    authDomain: 'taskmanager-1dc4d.firebaseapp.com',
    storageBucket: 'taskmanager-1dc4d.firebasestorage.app',
  );

}